services:

  db:
    image: postgres:14-alpine
    networks:
    - default
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=guests_db
    volumes:
      - postgres_data:/mount/var/lib/postgresql/data/

  backend:
    container_name: backend
    networks:
    - default
    build: .
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/guests_db
      - FLASK_ENV=development
    depends_on:
      - db

volumes:
  postgres_data:
